const mongoose = require('mongoose');

const blindFolk = mongoose.Schema(
    {
    mobile:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    age:{
        type:Number,
        required:true
    },
    examname:{
        type:String,
        required:true
    },
    subjectname:{
        type:String,
        required:true
    },
    examlanguage:{
        type:String,
        required:true
    },
    examdate:{
        type:Date,
        required:true
    },
    examtime:{
        type:String,
        required:true
    },
    examduration:
    {
        type:Number,
        required:true
    },
    examcity:{
        type:String,
        required:true
    },
    examarea:{
        type:String,
        required:true
    },
    commuteToWriter:{
        type:Boolean,
        required:true
    },
    requestStatus:{
        type:Boolean,
        default:false
    },
    writerId:{
        type:String,
        default:null
    }
},
    {
        timestamps:true
    }
);

module.exports = mongoose.model('blindfolk',blindFolk);